plot = read.csv("plot.csv", header = FALSE)
png(filename="plot.png")
par(mfrow=c(2,2))
boxplot(plot$V1, main="Normal password entry", ylab="Time in seconds")
boxplot(plot$V2, main="Slightly faster entry", ylab="Time in seconds")
boxplot(plot$V3, main="Slightly slower entry", ylab="Time in seconds")
boxplot(plot$V4, main="Recently entered data", ylab="Time in seconds")
dev.off()
